version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports: 
       - 80:3000
    depends_on:
       - db
    environment:
       DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:11.0-alpine
